// components/vue/testComponent3/Table.vue
<template>
    <table>
        <thead>
            <th v-for="heading in headings">
                {{heading}}
            </th>
        </thead>
        <tbody>
            <tr v-for="rowValues in rows">
                <td v-for="rowValue in rowValues">
                    {{rowValue}}
                </td>
            </tr>
        </tbody>
    </table>
</template>

<script>
    export default {
        props: ['tabledata'],
        computed: {
            headings: function() {
                return Object.keys(this.tabledata[0])
            },
            rows: function() {
                return this.tabledata.map((datum) => (Object.values(datum)))
            }
        }
    }
</script>

// components/react/common/Table.jsx
import React, {Component} from 'react';

const TableHeader = ({data}) => (
    <thead>
        <tr>
            {
                Object.keys(data[0]).map((key, idx) => (
                    <th key={`${key}_${idx}`}>
                        {key}
                    </th>
                ))
            }
        </tr>
    </thead>
);

const TableBody = ({data}) => (
    <tbody>
    {
        data.map((datum) => (
            <tr>
                {
                    Object.values(datum).map((value) => (
                        <td>{value}</td>
                    ))
                }
            </tr>
        ))
    }
    </tbody>
);

const Table = ({data, classNames}) => (
    <table className={classNames}>
        <TableHeader data={data}/>
        <TableBody data={data}/>
    </table>
);

export default Table;
